import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { NextUI } from "@/providers/nextui-provider";
import { ThemeProvider } from "@/providers/next-theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import LeftSidebar from "@/components/shared/LeftSidebar";
import Bottombar from "@/components/shared/Bottombar";
import RightSidebar from "@/components/shared/RightSidebar";
import Topbar from "@/components/shared/Topbar";
import Navigationbar from "@/components/shared/navigationbar";
export const metadata: Metadata = {
  title: "Next Color Picker  Beta",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/svg/Next-Color-Pick-Dark.svg",
        href: "/svg/Next-Color-Pick-Dark.svg",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/svg/Next-Color-Pick-Light.svg",
        href: "/svg/Next-Color-Pick-Light.svg",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body
          className={`font-Degular selection:bg-darkviolet selection:text-white`}
        >
          <NextUI>
            <ThemeProvider
              themes={["light", "dark"]}
              attribute="class"
              defaultTheme="system"
              enableSystem
              storageKey="next-color-pick-key"
            >
              <Navigationbar />

              <main className="flex flex-row">
                <LeftSidebar />
                <section className="flex min-h-screen flex-1 flex-col items-center px-6 pb-10 pt-28 max-md:pb-32 sm:px-10">
                  <div className="w-full max-w-4xl">{children}</div>
                </section>
                {/* @ts-ignore */}
                <RightSidebar />
              </main>

              <Bottombar />
            </ThemeProvider>
          </NextUI>
        </body>
      </html>
    </ClerkProvider>
  );
}
