import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { NextUI } from "@/providers/nextui-provider";
import { ThemeProvider } from "@/providers/next-theme-provider";
import { Toaster } from "sonner";
import Navigationbar from "@/components/navigationbar";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Next Color Picker  Beta",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        media: "(prefers-color-scheme: light)",
        url: "/svg/Next-Color-Pick-Dark.svg",
        href: "/svg/Next-Color-Pick-Dark.svg",
      },
      {
        media: "(prefers-color-scheme: dark)",
        url: "/svg/Next-Color-Pick-Light.svg",
        href: "/svg/Next-Color-Pick-Light.svg",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`font-Degular selection:bg-darkviolet selection:text-white`}
      >
        <NextUI>
          <ThemeProvider
            themes={["light", "dark"]}
            attribute="class"
            defaultTheme="system"
            enableSystem
            storageKey="next-color-pick-key"
          >
            <Toaster position="top-center" richColors />

            <Navigationbar/>

            {children}
          </ThemeProvider>
        </NextUI>
      </body>
    </html>
  );
}
