import React from "react";
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { NextUI } from "@/providers/nextui-provider";
import { ThemeProvider } from "@/providers/next-theme-provider";

import "../globals.css";



export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang='en' suppressHydrationWarning>
        <body className={`font-Degular flex min-h-screen flex-col items-center justify-between p-24`}> <NextUI>
            <ThemeProvider
              themes={["light", "dark"]}
              attribute="class"
              defaultTheme="system"
              enableSystem
              storageKey="next-color-pick-key"
            >
              

              {children}
            </ThemeProvider>
          </NextUI></body>
      </html>
    </ClerkProvider>
  );
}
